export const removecard = async (req, res ) => {
    try{
        const {cardId}= req.body;
        const agent = await CardModel.findById(cardId);
        if(!agent){
            return res.status(200).json({
                status: 'failed',
                message: 'agent not found'
            })
        }else{
            await CardModel.findByIdAndDelete(cardId);
            return res.status(200).json({
                status:" success",
                message: 'deleted successfully'
            })
        }    is there any error ?